% Loading functions and Data generation
addpath(genpath('../GitHub/mapping-inference'));
load('../Environments/SummaryData1Prior1Assignment1Model1Single1Multi1Plane2Weights1Density2Sparsity2Kill1.mat');
%%

%% run the Gibbs sampler
[gain_samples, gamma_samples] = Gibbs_first_spike(mpp, ...
    target_locations, cell_locations,...
    current_template, shape_template,delay_params,linkfunc,...
    stim_threshold, g, background_rate,v_th_known,...
    gain_grid, gain_prior, gamma_grid,gamma_prior,...
    gamma_initial,gain_initial,n_gibbs_sample);